const STAFF_LOGIN = 'STAFF_LOGIN';
const STAFF_LOGIN_SUCCESS = 'STAFF_LOGIN_SUCCESS';
const STAFF_LOGIN_FAILURE = 'STAFF_LOGIN_FAILURE';
const STAFF_SESSION = 'STAFF_SESSION';
const STAFF_SESSION_SUCCESS = 'STAFF_SESSION_SUCCESS';
const STAFF_SESSION_FAILURE = 'STAFF_SESSION_FAILURE';
const STAFF_LOGOUT = 'STAFF_LOGOUT';
const STAFF_LOGOUT_SUCCESS = 'STAFF_LOGOUT_SUCCESS';
const STAFF_LOGOUT_FAILURE = 'STAFF_LOGOUT_FAILURE';
const STAFF_GET = 'STAFF_GET';
const STAFF_GET_SUCCESS = 'STAFF_GET_SUCCESS';
const STAFF_GET_FAILURE = 'STAFF_GET_FAILURE';
const STAFF_GETLIST = 'STAFF_GETLIST';
const STAFF_GETLIST_SUCCESS = 'STAFF_GETLIST_SUCCESS';
const STAFF_GETLIST_FAILURE = 'STAFF_GETLIST_FAILURE';
const STAFF_INSERT = 'STAFF_INSERT';
const STAFF_INSERT_SUCCESS = 'STAFF_INSERT_SUCCESS';
const STAFF_INSERT_FAILURE = 'STAFF_INSERT_FAILURE';
const STAFF_MODIFY = 'STAFF_MODIFY';
const STAFF_MODIFY_SUCCESS = 'STAFF_MODIFY_SUCCESS';
const STAFF_MODIFY_FAILURE = 'STAFF_MODIFY_FAILURE';
const STAFF_REMOVE = 'STAFF_REMOVE';
const STAFF_REMOVE_SUCCESS = 'STAFF_REMOVE_SUCCESS';
const STAFF_REMOVE_FAILURE = 'STAFF_REMOVE_FAILURE';
const STAFF_REMOVEALL = 'STAFF_REMOVEALL';
const STAFF_REMOVEALL_SUCCESS = 'STAFF_REMOVEALL_SUCCESS';
const STAFF_REMOVEALL_FAILURE = 'STAFF_REMOVEALL_FAILURE';
const CUSTOMER_GET = 'CUSTOMER_GET';
const CUSTOMER_GET_SUCCESS = 'CUSTOMER_GET_SUCCESS';
const CUSTOMER_GET_FAILURE = 'CUSTOMER_GET_FAILURE';
const CUSTOMER_GETLIST = 'CUSTOMER_GETLIST';
const CUSTOMER_GETLIST_SUCCESS = 'CUSTOMER_GETLIST_SUCCESS';
const CUSTOMER_GETLIST_FAILURE = 'CUSTOMER_GETLIST_FAILURE';
const CUSTOMER_INSERT = 'CUSTOMER_INSERT';
const CUSTOMER_INSERT_SUCCESS = 'CUSTOMER_INSERT_SUCCESS';
const CUSTOMER_INSERT_FAILURE = 'CUSTOMER_INSERT_FAILURE';
const CUSTOMER_MODIFY = 'CUSTOMER_MODIFY';
const CUSTOMER_MODIFY_SUCCESS = 'CUSTOMER_MODIFY_SUCCESS';
const CUSTOMER_MODIFY_FAILURE = 'CUSTOMER_MODIFY_FAILURE';
const CUSTOMER_REMOVE = 'CUSTOMER_REMOVE';
const CUSTOMER_REMOVE_SUCCESS = 'CUSTOMER_REMOVE_SUCCESS';
const CUSTOMER_REMOVE_FAILURE = 'CUSTOMER_REMOVE_FAILURE';
const CUSTOMER_REMOVEALL = 'CUSTOMER_REMOVEALL';
const CUSTOMER_REMOVEALL_SUCCESS = 'CUSTOMER_REMOVEALL_SUCCESS';
const CUSTOMER_REMOVEALL_FAILURE = 'CUSTOMER_REMOVEALL_FAILURE';
const CUSTOMER_EXCEL = 'CUSTOMER_EXCEL';
const CUSTOMER_EXCEL_SUCCESS = 'CUSTOMER_EXCEL_SUCCESS';
const CUSTOMER_EXCEL_FAILURE = 'CUSTOMER_EXCEL_FAILURE';
const CUSTOMER_EXCELDOWNLOAD = 'CUSTOMER_EXCELDOWNLOAD';
const CUSTOMER_EXCELDOWNLOAD_SUCCESS = 'CUSTOMER_EXCELDOWNLOAD_SUCCESS';
const CUSTOMER_EXCELDOWNLOAD_FAILURE = 'CUSTOMER_EXCELDOWNLOAD_FAILURE';
const CUSTOMER_BULKINSERT = 'CUSTOMER_BULKINSERT';
const CUSTOMER_BULKINSERT_SUCCESS = 'CUSTOMER_BULKINSERT_SUCCESS';
const CUSTOMER_BULKINSERT_FAILURE = 'CUSTOMER_BULKINSERT_FAILURE';
const MOVIE_GETLIST = 'MOVIE_GETLIST';
const MOVIE_GETLIST_SUCCESS = 'MOVIE_GETLIST_SUCCESS';
const MOVIE_GETLIST_FAILURE = 'MOVIE_GETLIST_FAILURE';
const MOVIE_INSERT = 'MOVIE_INSERT';
const MOVIE_INSERT_SUCCESS = 'MOVIE_INSERT_SUCCESS';
const MOVIE_INSERT_FAILURE = 'MOVIE_INSERT_FAILURE';
const MOVIE_MODIFY = 'MOVIE_MODIFY';
const MOVIE_MODIFY_SUCCESS = 'MOVIE_MODIFY_SUCCESS';
const MOVIE_MODIFY_FAILURE = 'MOVIE_MODIFY_FAILURE';
const MOVIE_REMOVE = 'MOVIE_REMOVE';
const MOVIE_REMOVE_SUCCESS = 'MOVIE_REMOVE_SUCCESS';
const MOVIE_REMOVE_FAILURE = 'MOVIE_REMOVE_FAILURE';
const MOVIE_REMOVEALL = 'MOVIE_REMOVEALL';
const MOVIE_REMOVEALL_SUCCESS = 'MOVIE_REMOVEALL_SUCCESS';
const MOVIE_REMOVEALL_FAILURE = 'MOVIE_REMOVEALL_FAILURE';
const MOVIE_EXCEL = 'MOVIE_EXCEL';
const MOVIE_EXCEL_SUCCESS = 'MOVIE_EXCEL_SUCCESS';
const MOVIE_EXCEL_FAILURE = 'MOVIE_EXCEL_FAILURE';
const MOVIE_BULKINSERT = 'MOVIE_BULKINSERT';
const MOVIE_BULKINSERT_SUCCESS = 'MOVIE_BULKINSERT_SUCCESS';
const MOVIE_BULKINSERT_FAILURE = 'MOVIE_BULKINSERT_FAILURE';
const BUS_GET = 'BUS_GET';
const BUS_GET_SUCCESS = 'BUS_GET_SUCCESS';
const BUS_GET_FAILURE = 'BUS_GET_FAILURE';
const BUS_GETLIST = 'BUS_GETLIST';
const BUS_GETLIST_SUCCESS = 'BUS_GETLIST_SUCCESS';
const BUS_GETLIST_FAILURE = 'BUS_GETLIST_FAILURE';
const BUS_INSERT = 'BUS_INSERT';
const BUS_INSERT_SUCCESS = 'BUS_INSERT_SUCCESS';
const BUS_INSERT_FAILURE = 'BUS_INSERT_FAILURE';
const BUS_MODIFY = 'BUS_MODIFY';
const BUS_MODIFY_SUCCESS = 'BUS_MODIFY_SUCCESS';
const BUS_MODIFY_FAILURE = 'BUS_MODIFY_FAILURE';
const BUS_REMOVE = 'BUS_REMOVE';
const BUS_REMOVE_SUCCESS = 'BUS_REMOVE_SUCCESS';
const BUS_REMOVE_FAILURE = 'BUS_REMOVE_FAILURE';
const BUS_REMOVEALL = 'BUS_REMOVEALL';
const BUS_REMOVEALL_SUCCESS = 'BUS_REMOVEALL_SUCCESS';
const BUS_REMOVEALL_FAILURE = 'BUS_REMOVEALL_FAILURE';
const HISTORY_GETLIST = 'HISTORY_GETLIST';
const HISTORY_GETLIST_SUCCESS = 'HISTORY_GETLIST_SUCCESS';
const HISTORY_GETLIST_FAILURE = 'HISTORY_GETLIST_FAILURE';
const HISTORY_REMOVEALL = 'HISTORY_REMOVEALL';
const HISTORY_REMOVEALL_SUCCESS = 'HISTORY_REMOVEALL_SUCCESS';
const HISTORY_REMOVEALL_FAILURE = 'HISTORY_REMOVEALL_FAILURE';
const RESERVATION_GETLIST = 'RESERVATION_GETLIST';
const RESERVATION_GETLIST_SUCCESS = 'RESERVATION_GETLIST_SUCCESS';
const RESERVATION_GETLIST_FAILURE = 'RESERVATION_GETLIST_FAILURE';
const RESERVATION_INSERT = 'RESERVATION_INSERT';
const RESERVATION_INSERT_SUCCESS = 'RESERVATION_INSERT_SUCCESS';
const RESERVATION_INSERT_FAILURE = 'RESERVATION_INSERT_FAILURE';
const RESERVATION_REMOVE = 'RESERVATION_REMOVE';
const RESERVATION_REMOVE_SUCCESS = 'RESERVATION_REMOVE_SUCCESS';
const RESERVATION_REMOVE_FAILURE = 'RESERVATION_REMOVE_FAILURE';
const RESERVATION_REMOVEALL = 'RESERVATION_REMOVEALL';
const RESERVATION_REMOVEALL_SUCCESS = 'RESERVATION_REMOVEALL_SUCCESS';
const RESERVATION_REMOVEALL_FAILURE = 'RESERVATION_REMOVEALL_FAILURE';
const WORK_GETLIST = 'WORK_GETLIST';
const WORK_GETLIST_SUCCESS = 'WORK_GETLIST_SUCCESS';
const WORK_GETLIST_FAILURE = 'WORK_GETLIST_FAILURE';
const WORK_INSERT = 'WORK_INSERT';
const WORK_INSERT_SUCCESS = 'WORK_INSERT_SUCCESS';
const WORK_INSERT_FAILURE = 'WORK_INSERT_FAILURE';
const WORK_MODIFY = 'WORK_MODIFY';
const WORK_MODIFY_SUCCESS = 'WORK_MODIFY_SUCCESS';
const WORK_MODIFY_FAILURE = 'WORK_MODIFY_FAILURE';
const WORK_REMOVE = 'WORK_REMOVE';
const WORK_REMOVE_SUCCESS = 'WORK_REMOVE_SUCCESS';
const WORK_REMOVE_FAILURE = 'WORK_REMOVE_FAILURE';
const WORK_REMOVEALL = 'WORK_REMOVEALL';
const WORK_REMOVEALL_SUCCESS = 'WORK_REMOVEALL_SUCCESS';
const WORK_REMOVEALL_FAILURE = 'WORK_REMOVEALL_FAILURE';
const WORK_EXCELDOWNLOAD = 'WORK_EXCELDOWNLOAD';
const WORK_EXCELDOWNLOAD_SUCCESS = 'WORK_EXCELDOWNLOAD_SUCCESS';
const WORK_EXCELDOWNLOAD_FAILURE = 'WORK_EXCELDOWNLOAD_FAILURE';
const WORK_BULKINSERT = 'WORK_BULKINSERT';
const WORK_BULKINSERT_SUCCESS = 'WORK_BULKINSERT_SUCCESS';
const WORK_BULKINSERT_FAILURE = 'WORK_BULKINSERT_FAILURE';
const THEATER_GETLIST = 'THEATER_GETLIST';
const THEATER_GETLIST_SUCCESS = 'THEATER_GETLIST_SUCCESS';
const THEATER_GETLIST_FAILURE = 'THEATER_GETLIST_FAILURE';
const THEATER_INSERT = 'THEATER_INSERT';
const THEATER_INSERT_SUCCESS = 'THEATER_INSERT_SUCCESS';
const THEATER_INSERT_FAILURE = 'THEATER_INSERT_FAILURE';
const THEATER_MODIFY = 'THEATER_MODIFY';
const THEATER_MODIFY_SUCCESS = 'THEATER_MODIFY_SUCCESS';
const THEATER_MODIFY_FAILURE = 'THEATER_MODIFY_FAILURE';
const THEATER_REMOVE = 'THEATER_REMOVE';
const THEATER_REMOVE_SUCCESS = 'THEATER_REMOVE_SUCCESS';
const THEATER_REMOVE_FAILURE = 'THEATER_REMOVE_FAILURE';
const THEATER_REMOVEALL = 'THEATER_REMOVEALL';
const THEATER_REMOVEALL_SUCCESS = 'THEATER_REMOVEALL_SUCCESS';
const THEATER_REMOVEALL_FAILURE = 'THEATER_REMOVEALL_FAILURE';
export {
  STAFF_LOGIN,
  STAFF_LOGIN_SUCCESS,
  STAFF_LOGIN_FAILURE,
  STAFF_SESSION,
  STAFF_SESSION_SUCCESS,
  STAFF_SESSION_FAILURE,
  STAFF_LOGOUT,
  STAFF_LOGOUT_SUCCESS,
  STAFF_LOGOUT_FAILURE,
  STAFF_GET,
  STAFF_GET_SUCCESS,
  STAFF_GET_FAILURE,
  STAFF_GETLIST,
  STAFF_GETLIST_SUCCESS,
  STAFF_GETLIST_FAILURE,
  STAFF_INSERT,
  STAFF_INSERT_SUCCESS,
  STAFF_INSERT_FAILURE,
  STAFF_MODIFY,
  STAFF_MODIFY_SUCCESS,
  STAFF_MODIFY_FAILURE,
  STAFF_REMOVE,
  STAFF_REMOVE_SUCCESS,
  STAFF_REMOVE_FAILURE,
  STAFF_REMOVEALL,
  STAFF_REMOVEALL_SUCCESS,
  STAFF_REMOVEALL_FAILURE,
  CUSTOMER_GET,
  CUSTOMER_GET_SUCCESS,
  CUSTOMER_GET_FAILURE,
  CUSTOMER_GETLIST,
  CUSTOMER_GETLIST_SUCCESS,
  CUSTOMER_GETLIST_FAILURE,
  CUSTOMER_INSERT,
  CUSTOMER_INSERT_SUCCESS,
  CUSTOMER_INSERT_FAILURE,
  CUSTOMER_MODIFY,
  CUSTOMER_MODIFY_SUCCESS,
  CUSTOMER_MODIFY_FAILURE,
  CUSTOMER_REMOVE,
  CUSTOMER_REMOVE_SUCCESS,
  CUSTOMER_REMOVE_FAILURE,
  CUSTOMER_REMOVEALL,
  CUSTOMER_REMOVEALL_SUCCESS,
  CUSTOMER_REMOVEALL_FAILURE,
  CUSTOMER_EXCEL,
  CUSTOMER_EXCEL_SUCCESS,
  CUSTOMER_EXCEL_FAILURE,
  CUSTOMER_EXCELDOWNLOAD,
  CUSTOMER_EXCELDOWNLOAD_SUCCESS,
  CUSTOMER_EXCELDOWNLOAD_FAILURE,
  CUSTOMER_BULKINSERT,
  CUSTOMER_BULKINSERT_SUCCESS,
  CUSTOMER_BULKINSERT_FAILURE,
  MOVIE_GETLIST,
  MOVIE_GETLIST_SUCCESS,
  MOVIE_GETLIST_FAILURE,
  MOVIE_INSERT,
  MOVIE_INSERT_SUCCESS,
  MOVIE_INSERT_FAILURE,
  MOVIE_MODIFY,
  MOVIE_MODIFY_SUCCESS,
  MOVIE_MODIFY_FAILURE,
  MOVIE_REMOVE,
  MOVIE_REMOVE_SUCCESS,
  MOVIE_REMOVE_FAILURE,
  MOVIE_REMOVEALL,
  MOVIE_REMOVEALL_SUCCESS,
  MOVIE_REMOVEALL_FAILURE,
  MOVIE_EXCEL,
  MOVIE_EXCEL_SUCCESS,
  MOVIE_EXCEL_FAILURE,
  MOVIE_BULKINSERT,
  MOVIE_BULKINSERT_SUCCESS,
  MOVIE_BULKINSERT_FAILURE,
  BUS_GET,
  BUS_GET_SUCCESS,
  BUS_GET_FAILURE,
  BUS_GETLIST,
  BUS_GETLIST_SUCCESS,
  BUS_GETLIST_FAILURE,
  BUS_INSERT,
  BUS_INSERT_SUCCESS,
  BUS_INSERT_FAILURE,
  BUS_MODIFY,
  BUS_MODIFY_SUCCESS,
  BUS_MODIFY_FAILURE,
  BUS_REMOVE,
  BUS_REMOVE_SUCCESS,
  BUS_REMOVE_FAILURE,
  BUS_REMOVEALL,
  BUS_REMOVEALL_SUCCESS,
  BUS_REMOVEALL_FAILURE,
  HISTORY_GETLIST,
  HISTORY_GETLIST_SUCCESS,
  HISTORY_GETLIST_FAILURE,
  HISTORY_REMOVEALL,
  HISTORY_REMOVEALL_SUCCESS,
  HISTORY_REMOVEALL_FAILURE,
  RESERVATION_GETLIST,
  RESERVATION_GETLIST_SUCCESS,
  RESERVATION_GETLIST_FAILURE,
  RESERVATION_INSERT,
  RESERVATION_INSERT_SUCCESS,
  RESERVATION_INSERT_FAILURE,
  RESERVATION_REMOVE,
  RESERVATION_REMOVE_SUCCESS,
  RESERVATION_REMOVE_FAILURE,
  RESERVATION_REMOVEALL,
  RESERVATION_REMOVEALL_SUCCESS,
  RESERVATION_REMOVEALL_FAILURE,
  WORK_GETLIST,
  WORK_GETLIST_SUCCESS,
  WORK_GETLIST_FAILURE,
  WORK_INSERT,
  WORK_INSERT_SUCCESS,
  WORK_INSERT_FAILURE,
  WORK_MODIFY,
  WORK_MODIFY_SUCCESS,
  WORK_MODIFY_FAILURE,
  WORK_REMOVE,
  WORK_REMOVE_SUCCESS,
  WORK_REMOVE_FAILURE,
  WORK_REMOVEALL,
  WORK_REMOVEALL_SUCCESS,
  WORK_REMOVEALL_FAILURE,
  WORK_EXCELDOWNLOAD,
  WORK_EXCELDOWNLOAD_SUCCESS,
  WORK_EXCELDOWNLOAD_FAILURE,
  WORK_BULKINSERT,
  WORK_BULKINSERT_SUCCESS,
  WORK_BULKINSERT_FAILURE,
  THEATER_GETLIST,
  THEATER_GETLIST_SUCCESS,
  THEATER_GETLIST_FAILURE,
  THEATER_INSERT,
  THEATER_INSERT_SUCCESS,
  THEATER_INSERT_FAILURE,
  THEATER_MODIFY,
  THEATER_MODIFY_SUCCESS,
  THEATER_MODIFY_FAILURE,
  THEATER_REMOVE,
  THEATER_REMOVE_SUCCESS,
  THEATER_REMOVE_FAILURE,
  THEATER_REMOVEALL,
  THEATER_REMOVEALL_SUCCESS,
  THEATER_REMOVEALL_FAILURE,
};
